<div style="color:red;background-color:black">
Diamond Light Source
<br style="color:red;background-color:antiquewhite"><h1>Numpy Questions<br></h1>  

©2000-20 Chris Seddon

## Q1
Create 4x6 array of floats between 3.5 and 5.5.  Display the results to 3 decimal 
places using `set_printoptions`.

In [ ]:
# Write YOUR code here

## Q2
Create a 4x6 array of random ints between 10 and 100.

In [ ]:
# Write YOUR code here

## Q3
Create another 4x6 array of random ints between 10 and 100.  Then set all the even
numbers to 100.

In [ ]:
# Write YOUR code here
index

## Q4
Create another 4x6 array of random ints between 10 and 100.  Create a new 1D array
with all the numbers in the first array that are less than 50.

In [ ]:
# Write YOUR code here

## Q5
Create a 4x6 array of random integers between 10 and 100.
Create a new 4x3 array of the lowest 50% of the original array whilst 
preserving order.

In [ ]:
# Write YOUR code here

## Q6
Create a 4x6 array of random integers between 10 and 100.
Set the lowest 50% of the array to 0.

In [ ]:
# Write YOUR code here

## Q7
Create a 6x4 array of ints where the first row is filled
with 10, the second with 11, the third with 12 and the last with 13.

In [ ]:
# Write YOUR code here

## Q8
Create a 8x5 array of ints using the "tile" method so that each successive row is rotated left.  The solution should look like:

    [[10 11 12 13 10]
     [11 12 13 10 11]
     [12 13 ... 
           ... 11 12]
     [13 10 11 12 13]]

In [ ]:
# Write YOUR code here

## Q9
Create a 4x6 array of ints.  Then create a new array with columns 2 and 4 of the original array swapped.

In [ ]:
# Write YOUR code here

## Q10
Create a 3x10 array.  Use the `rot90` method to rotate the array by 90 degrees.  Repeat this 4 times, so you get back
to the original array, printing the contents of the array on each step.

In [ ]:
# Write YOUR code here

## Q11
Find the common elements of two 1D arrays below using the `intersect1d` method. 
<pre>
a = np.array([5,6,1,5,0,4,6,10,11,2,3])
b = np.array([6,2,10,9,4,9,3,2,1])
</pre>

In [ ]:
# Write YOUR code here

## Q12
Create two 1D int arrays of equal size.  Then create a new array of the same size, selecting elements from the first array when the element in this array is even, and selecting elements from the second array 
when the element in the first array is odd.  
Use the following arrays as sample data:
<pre>
a = np.arange(10,50,3)
b = np.arange(100,114)
</pre>

In [ ]:
# Write YOUR code here

## Q13
Create a 4x6 array of random ints between 10 and 100.  Use the Numpy documentation to see what it means to define a masked array and then create a masked array where all values in the original array that are less than 50 are masked out.

In [ ]:
# Write YOUR code here

## Q14
Create a 4x6 array of random ints between 10 and 100.  
Filter this array to produce a new 1D array consisting of only the numbers divisible by 3 in the original array.

In [ ]:
# Write YOUR code here

## Q15
Create a 4x6 array of random ints between 10 and 100.  Then create a 4x6 array of indices of representing rankings of the first array.

For example the 2x3 array
<pre>
    [[49 56 61]
     [63 39 97]]
</pre>
yields the rankings
<pre>
    [[4 0 1]
     [2 3 5]]
</pre>

In [ ]:
# Write YOUR code here

## Q16
Create a 1D array of random ints of size (30,) containing only the numbers 10, 11, 12, 13 or 14. Now create 30 'one hot encodings' for the original array.  You can read up about 'one hot encodings' on the web.  

For example a set of 'one hot encodings' for:
<pre>
    [20, 22, 21, 22, 20, 22]
</pre>
would be:
<pre>
    [1 0 0]
    [0 0 1]
    [0 1 0]
    [0 0 1]
    [1 0 0]
    [0 0 1]
</pre>

In [ ]:
# Write YOUR code here

## Q17
Create two vectors representing points in 3D space.  Now calculate the distance between these points.

In [ ]:
# Write YOUR code here

## Q18
Write a function that performs a 3D Cartesian to Spherical coordinate transformation on vectors.  Perform a Cartesian to Spherical coordinate transformation on each of
the Cartesian unit vectors:
<pre>
    iHat = [1, 0, 0]
    jHat = [0, 1, 0]
    kHat = [0, 0, 1]
</pre>
Note that the transfomation for kHat causes a singularity in Spherical coordinates, so try vectors very near kHat instead:
<pre>
    kHat_plus  = [+0.0001,0,1])
    kHat_minus = [-0.0001,0,1])
</pre>

In [ ]:
# Write YOUR code here